name: SonarCloud Scan

on:
  workflow_run:
    workflows: ['Unit Test & Coverage']
    types:
      - completed
jobs:
  Process:
    if: github.event.workflow_run.conclusion != 'failure'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Extract Maven project version
      run: echo ::set-output name=version::$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
      id: project
    - name: Prepare changelog
      run: |
        sed -i -e "s|<sonar.organization>${env.SONAR_ORGANIZATION}</sonar.organization>|sonar.projectKey=<sonar.organization>${{ secrets.SONAR_ORGANIZATION }}</sonar.organization>|g" sonar-project.properties
    - name: Build and analyze
      run: > 
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar    
            -Denv.SONAR_ORGANIZATION=${{ secrets.SONAR_ORGANIZATION }}
            -Dsonar.projectName=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.version=${{ steps.project.outputs.version }}
            -Dsonar.java.binaries=.
            -Dsonar.sources=.
            -Dsonar.inclusions=/*.java
            -Dsonar.exclusions=/*.zip,/*.jar,/*.html,/R.java,/build/,/target/,/.settings/,/.mvn/,/src/main/resources/static/bower_components/,/src/main/resources/static/jquery-validation/,/src/main/resources/static/scripts/material/,/src/main/resources/static/scripts/multiselect/,/src/main/resources/static/scripts/nanobar/,/src/main/resources/static/scripts/plugins/,/src/main/resources/static/scripts/utils/**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}