name: 'Unit Test Reporter'

on:
  workflow_run:
    workflows: ['Unit Test & Coverage']
    types:
      - completed
jobs:
  Check:
    runs-on: ubuntu-latest
    outputs:
      isPR: ${{ steps.main_pr.outputs.valid }}
      isPush: ${{ steps.main_push.outputs.valid }}
    env:
      isPR: ${{ github.event.workflow_run.conclusion == 'failure' || github.event.workflow_run.event == 'pull_request' }}
      isPush: ${{ github.event.workflow_run.event == 'push' }}
    steps:
      - name: Check PR
        id: main_pr
        run: echo '::set-output name=valid::${{ env.isPR }}'
      - name: Check Push
        id: main_push
        run: echo '::set-output name=valid::${{ env.isPush }}'
  Result:
    runs-on: ubuntu-latest
    needs: [Check]
    if: needs.Check.outputs.isPR == 'true' || needs.Check.outputs.isPush == 'true'
    env:
      artifactName: 'test-results'
    steps:
    - name: Download Artifacts
      uses: actions/github-script@v6
      with:
        script: |
          const workflowInfo = await github.rest.actions.listWorkflowRunArtifacts({
            ...context.repo,
            run_id: ${{ github.event.workflow_run.id }}
          })
          if (workflowInfo.data.artifacts.length === 0) {
            console.log(`No artifact on previous workflow`)
            return
          }
          const artifacts = workflowInfo.data.artifacts.filter(a => a.name == "${{ env.artifactName }}")
          if (artifacts.length === 0) {
            console.log(`No artifact named ${{ env.artifactName }}`)
            return
          }
          const artifact = artifacts[0]    
          const download = await github.rest.actions.downloadArtifact({
            artifact_id: artifact.id,
            archive_format: 'zip',
            ...context.repo
          })
          const fs = require('fs');
          fs.writeFileSync('${{env.artifactName}}.zip', Buffer.from(download.data));
    - name: Extract
      run: unzip ${{env.artifactName}}.zip
    - run: echo '${{ toJson(github) }}'
    - name: Create Report
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: '*.xml'
